examples/react-native/hot-updater.config.ts, packages/hot-updater/src/commands/deploy.ts, packages/hot-updater/src/helper.ts, packages/hot-updater/src/utils/areBuildHashesIncluded.ts, packages/hot-updater/src/utils/getFileHash.ts, packages/internal/src/filterTargetVersion.ts, packages/internal/src/types.ts, plugins/aws/src/aws.ts, plugins/aws/src/index.ts, plugins/metro/src/index.ts
=> feat: already update guard

packages/console/src/routes/_components/edit-bundle-sheet-content.tsx
=> feat(console): always show gitCommitHash

packages/core/src/test-utils/setupSemverSatisfiesTestSuite.ts, plugins/postgres/sql/semver_satisfies.sql, plugins/supabase/supabase/migrations/20250103114225_init.sql
=> fix(postgres): `semver_match` sql more test

plugins/metro/src/index.ts
=> feat(metro): add `entryFile`, `sourcemap` parameter to metro()

plugins/supabase/src/supabaseStorage.ts
=> refactor(supabase): improve error message for upload failures 

packages/core/src/index.ts, packages/react-native/src/index.ts, packages/react-native/src/native.ts
=> fix(react-native): compatibility with TypeScript 4

packages/react-native/src/runUpdateProcess.ts
Make the wrap the same as the default value.
=> feat(react-native): change default `reloadOnForceUpdate` to `true`

packages/react-native/android/src/main/java/com/hotupdater/HotUpdater.kt, packages/react-native/android/src/newarch/HotUpdaterModule.kt, packages/react-native/android/src/oldarch/HotUpdaterModule.kt, packages/react-native/android/src/oldarch/HotUpdaterSpec.kt
=> fix(android): Prevent bundle loading when URL is null

packages/react-native/android/proguard-rules.pro
Related https://github.com/gronxb/hot-updater/pull/107
=> fix(android): new arch ProGuard

packages/react-native/ios/HotUpdater/HotUpdater.mm
https://github.com/gronxb/hot-updater/pull/106
I’m reviving a missing part in this PR.
=> fix(ios): Add progress tracking for download tasks in HotUpdater

packages/react-native/ios/HotUpdater/HotUpdater.mm, packages/react-native/src/checkUpdate.ts
=> fix(ios): warn requiresMainQueueSetup

packages/console/src-server/rpc.ts, packages/console/src/App.tsx, packages/console/src/components/ui/skeleton.tsx, packages/console/src/lib/api.ts, packages/console/src/routes/_components/edit-bundle-sheet-content.tsx, packages/console/src/routes/index.tsx
Before using query, there were many calls api by refresh, click to sidebar, and so on.
so I added query to them.
=> refactor(console): improve network and UX  by query cache

examples/v0.77.0/hot-updater.config.ts, package.json, plugins/firebase/package.json, plugins/firebase/rslib.config.ts, plugins/firebase/src/firebaseStorage.ts, plugins/firebase/src/index.ts, plugins/firebase/tsconfig.json, pnpm-lock.yaml
issue #110 
I did the first step of firebase integration. I added firebaseStorage.
in firebase
1. make project
2. make webapp project
3. there are keys for environment variables
=> feat(firebase): integration `firebaseStorage`

packages/hot-updater/package.json, packages/hot-updater/src/commands/init/aws/index.ts, packages/hot-updater/src/commands/init/aws/regionLocationMap.ts, packages/hot-updater/src/commands/init/aws/transformEnv.spec.ts, packages/hot-updater/src/commands/init/aws/transformEnv.ts, plugins/aws/lambda/getUpdateInfo.ts, plugins/aws/lambda/index.ts, plugins/aws/package.json, pnpm-lock.yaml
=> fix(aws): fetch the correct S3 bucket regardless of region

docs/docs/guide/hot-updater/useHotUpdaterStore.mdx, examples/v0.71.19/App.tsx, examples/v0.74.1/App.tsx, examples/v0.76.1-new-arch/App.tsx, examples/v0.77.0/App.tsx, packages/react-native/package.json, packages/react-native/src/store.ts, pnpm-lock.yaml
=> fix(react-native): compat react 17

packages/console/src/App.tsx, packages/console/src/components/ui/toast.tsx, packages/console/src/routes/_components/columns.tsx
=> feat(console): icon colorful

packages/hot-updater/src/commands/init/aws/index.ts, packages/hot-updater/src/commands/init/supabase/index.ts, packages/hot-updater/src/commands/supabase/select.ts, plugins/cloudflare/src/utils/createWrangler.ts
=> fix(cli): windows migration command blocking

biome.json, packages/react-native/src/wrap.tsx
=> refactor(react-native): simplify import statement in wrap.tsx

packages/hot-updater/src/commands/deploy.ts, packages/hot-updater/src/utils/getBundleZipTargets.spec.ts, packages/hot-updater/src/utils/getBundleZipTargets.ts, plugins/metro/src/hermes.ts, plugins/plugin-core/src/createZip.ts
=> fix(metro): ensure `bundle.map` is generated correctly when `enableHermes` is set to true

packages/hot-updater/src/commands/init.ts, plugins/aws/package.json, plugins/cloudflare/package.json, plugins/supabase/package.json, pnpm-lock.yaml
=> chore(plugins): peerDeps @clack/prompts

docs/docs/guide/providers/3_aws-s3-lambda-edge.mdx, plugins/aws/iac/s3.ts
=> fix(aws): create s3 region us-east-1

packages/react-native/ios/HotUpdater/HotUpdater.mm
=> fix(ios): HotUpdater.reload should work properly even in debug mode

packages/hot-updater/package.json, pnpm-lock.yaml
Closed #252
Thanks for https://github.com/toss/es-git/issues/87
=> chore(cli): supports es-git linux arm64

packages/hot-updater/src/utils/getBundleZipTargets.ts
Closed #268 
Credit. @YspCoder
=> fix(cli): windows os createZip incorrect assets

packages/react-native/src/checkForUpdate.ts, packages/react-native/src/fetchUpdateInfo.ts
```ts
export default HotUpdater.wrap({
requestTimeout: 5000, // set you want timeout ms
```
=> feat(react-native): fetchUpdateInfo timeout default 5000

packages/react-native/src/checkForUpdate.ts, packages/react-native/src/fetchUpdateInfo.ts
Allowed #263 
```tsx
export default HotUpdater.wrap({
source: async () => {
const res = await fetch(
`${HOT_UPDATER_SUPABASE_URL}/functions/v1/update-server`,
);
return (await res.json()) as AppUpdateInfo | null;
},
}); 
```
```tsx
HotUpdater.runUpdateProcess({
source: async () => {
const res = await fetch(
`${HOT_UPDATER_SUPABASE_URL}/functions/v1/update-server`,
);
return (await res.json()) as AppUpdateInfo | null;
},
}); 
```
=> feat(react-native): source allow async function

CONTRIBUTION.md
I made contributing guide for first contributing.
Are there any some more contents?
=> docs(guide): contributing guide

plugins/firebase/iac/index.ts
In this URL, It occurs 404 error, It is not correct
https://gronxb.github.io/hot-updater/guide/getting-started/quick-start-with-firebase.html#step-4-add-hotupdater-to-your-project
->
https://gronxb.github.io/hot-updater/guide/providers/4_firebase.html#step-4-add-hotupdater-to-your-project
=> fix(firebase): edit URL for next step

plugins/supabase/iac/index.ts
=> fix(supabase): init correct supabase workdir

plugins/firebase/iac/index.ts, plugins/firebase/iac/select.ts
=> fix(firebase): supports windows init

docs/docs/guide/plugins/sentry.mdx
Hello,
I noticed that something was missing from the document, so I made some corrections.
I would appreciate it if you could take a look.
=> docs: update sentry

packages/react-native/src/checkForUpdate.ts, packages/react-native/src/runUpdateProcess.ts, packages/react-native/src/wrap.tsx
```tsx
const updateInfo = await HotUpdater.checkForUpdate({
source: "<your-update-server-url>",
requestHeaders: {
Authorization: "Bearer <your-access-token>",
},
});
if (!updateInfo) {
return {
status: "UP_TO_DATE",
};
}
// same as HotUpdater.updateBundle({ bundleId: updateInfo.id, fileUrl: updateInfo.fileUrl, status: updateInfo.status });
await updateInfo.updateBundle();
```
=> feat(react-native): HotUpdater.updateBundle prefill with checkForUpdate

.changeset/spotty-icons-dig.md, examples/v0.71.19/fingerprint.json, packages/hot-updater/src/index.ts
=> fix(cli): create fingerprint

.changeset/all-wombats-pay.md, examples/expo-52/android/app/src/main/res/values/strings.xml, examples/expo-52/fingerprint.json, examples/expo-52/ios/expo52/Info.plist, examples/rnef-repack/android/app/src/main/res/values/strings.xml, examples/rnef-repack/fingerprint.json, examples/rnef-repack/ios/rnef/Info.plist, examples/v0.71.19/android/app/src/main/res/values/strings.xml, examples/v0.71.19/fingerprint.json, examples/v0.71.19/ios/HotUpdaterExample/Info.plist, examples/v0.74.1/android/app/src/main/res/values/strings.xml, examples/v0.74.1/fingerprint.json, examples/v0.74.1/ios/HotUpdaterExample/Info.plist, examples/v0.76.1-new-arch/android/app/src/main/res/values/strings.xml, examples/v0.76.1-new-arch/fingerprint.json, examples/v0.76.1-new-arch/ios/HotUpdaterExample/Info.plist, packages/hot-updater/package.json, packages/hot-updater/src/commands/fingerprint.ts, packages/hot-updater/src/utils/configParser/iosParser.spec.ts, packages/hot-updater/src/utils/configParser/iosParser.ts, packages/hot-updater/src/utils/fingerprint/fingerprint.spec.ts, packages/hot-updater/src/utils/fingerprint/processExtraSources.ts, packages/hot-updater/src/utils/getIosAppTargetDirectoryName.ts, packages/hot-updater/src/utils/version/getIOSVersion.ts, packages/hot-updater/src/utils/version/getNativeAppVersion.spec.ts, plugins/firebase/.gitignore, plugins/plugin-core/src/test-utils/mockReactNativeProjectRoot.ts, pnpm-lock.yaml
=> fix(cli): globby to fast-glob

examples/expo-52/ios/Podfile.lock, examples/expo-52/ios/expo52.xcodeproj/project.pbxproj, examples/expo-52/package.json, pnpm-lock.yaml
I'm testing Android native build for expo example project and it isn't working with error.
I searched [a workaround](https://github.com/expo/eas-cli/issues/2789#issuecomment-2566609397) for this and applied and checked a successful build.
=> chore: fix expo example android build

.changeset/rare-cars-matter.md, packages/hot-updater/src/commands/deploy.ts, packages/hot-updater/src/commands/fingerprint.ts, packages/hot-updater/src/utils/fingerprint/common.ts, packages/hot-updater/src/utils/fingerprint/diff.ts, packages/hot-updater/src/utils/fingerprint/fingerprint.spec.ts, packages/hot-updater/src/utils/fingerprint/index.ts
=> feat(cli): show fingerprint diff

.changeset/warm-islands-pump.md, packages/react-native/package.json, packages/react-native/plugin/src/withHotUpdater.ts, pnpm-lock.yaml
=> Skip fingerprint generation when using appVersion strategy

.changeset/moody-beers-write.md, docs/docs/guide/plugins/datadog.mdx, plugins/datadog-plugin/CHANGELOG.md, plugins/datadog-plugin/package.json, plugins/datadog-plugin/src/index.ts, plugins/datadog-plugin/src/withDatadog.ts, plugins/datadog-plugin/tsconfig.json, plugins/datadog-plugin/tsdown.config.ts, pnpm-lock.yaml
Most of what has been done here derives from the Datadog documentation https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/react_native/error_tracking.
=> feat(datadog): Introduce Datadog plugin to upload sourcemaps

.changeset/eager-jobs-rest.md, packages/react-native/android/proguard-rules.pro
https://github.com/gronxb/hot-updater/issues/535
I fixed the proguard error that occurred during Android build.
=> fix(android): fix proguard syntax
