gronxb/hot-updater

- docs/docs/guide/hot-updater/wrap.mdx
- examples/v0.71.19/App.tsx
- examples/v0.74.1/App.tsx
- examples/v0.76.1-new-arch/App.tsx
- examples/v0.77.0/App.tsx
- packages/react-native/src/wrap.tsx
**Description**
In this PR, I have added status as a prop to the line 
`return <Fallback progress={progress} status={status} />; `
in the wrap.tsx file.
The purpose of adding the status prop is to allow the fallbackComponent to provide more dynamic and informative UI feedback based on the current update process.
> feat(react-native): add `status` to fallbackComponent in wrap function

- packages/react-native/android/build.gradle
- packages/react-native/android/proguard-rules.pro
No field mBundleLoader in class Lcom/facebook/react/ issue fixed
Closed #105
> fix(android): prevent ProGuard from blocking access to `mBundleLoader`

- packages/react-native/ios/HotUpdater/HotUpdater.h
- packages/react-native/ios/HotUpdater/HotUpdater.mm
> fix(ios): ensure UI thread is not blocked by sending events

- packages/console/src/routes/_components/edit-bundle-sheet-content.tsx
Previously, clicking the save button gave no feedback. I've added a loading signal so that a loading icon now appears when the button is pressed.
https://github.com/user-attachments/assets/7f3c6a8d-1bb7-46db-92f1-4d9a3632bc16
> feat(console): after clicking save, show loading icon

- packages/react-native/ios/HotUpdater/HotUpdater.mm
We have a brownfield app, meaning it originally started as a native app, and React Native was integrated later. As a result:
- The entry point is not React Native.
- We manually create the RCTBridge.
- Our AppDelegate does not conform to RCTAppDelegate.
During a forced OTA update (when reload = true), hot-updater triggers `RCTTriggerReloadCommandListeners` this leads to the following issue:
- `RCTTriggerReloadCommandListeners` reaches the registered bridge, which still points to the old bundle URL.
- App reloads the last set bundleUrl on that bridge, which is not the new one.
- The old bundle is loaded again triggering an update check and another reload.
- This creates an infinite reload loop, despite the new bundle being downloaded correctly.
Note that If reload is not triggered, the new …
> fix(ios): Update bundleUrl Before Reload for Custom RCTBridges

- plugins/aws/lambda/index.ts
- plugins/aws/tsup.config.ts
This PR includes the following changes:
1.	Modify build output to generate only CJS
•	Lambda@Edge supports only CommonJS (CJS), so the build process is adjusted to produce only CJS output.
2.	Return null instead of throwing an error when target-app-versions.json is not yet created
•	Previously, an error was thrown if target-app-versions.json was missing.
•	Now, it returns null to prevent unnecessary failures.
These changes improve compatibility with Lambda@Edge and enhance error handling. 🚀
> Ensure CJS-only build for Lambda@Edge and return null instead of error before target-app-versions.json creation

- examples/v0.71.19/App.tsx
- examples/v0.71.19/hot-updater.config.ts
- examples/v0.74.1/App.tsx
- examples/v0.74.1/hot-updater.config.ts
- examples/v0.76.1-new-arch/App.tsx
- examples/v0.76.1-new-arch/hot-updater.config.ts
- examples/v0.77.0/App.tsx
- examples/v0.77.0/hot-updater.config.ts
- examples/v0.77.0/ios/Podfile.lock
- packages/hot-updater/src/commands/deploy.ts
- packages/hot-updater/src/commands/init/cloudflareD1R2Worker/index.ts
- plugins/metro/package.json
- plugins/metro/src/hermes.ts
- plugins/metro/src/index.ts
- plugins/plugin-core/src/types.ts
Enabling Hermes compiles JavaScript to bytecode, improving performance and memory efficiency. If you’re using Hermes, it is recommended to enable this flag.
https://reactnative.dev/docs/hermes
```tsx
import { metro } from "@hot-updater/metro";
import { defineConfig } from "hot-updater";
import "dotenv/config";
export default defineConfig({
build: metro({
enableHermes: true,
}),
...
});
```
> feat(metro): `enableHermes` options

- packages/hot-updater/src/commands/init/cloudflareD1R2Worker/index.ts
After version 0.10.1, @gronxb added enableHermes options in the pull request https://github.com/gronxb/hot-updater/pull/120 that introduces a build failure.
I get the error when init the hot-updater using command `yarn hot-updater init`.
```
file:///Users/minhhieu76qng/dev/dsv/my-project/node_modules/hot-updater/dist/index.js:22416
paths: [
^
ReferenceError: getCwd is not defined
at deployWorker (file:///Users/minhhieu76qng/dev/dsv/my-project/node_modules/hot-updater/dist/index.js:22416:16)
at initCloudflareD1R2Worker (file:///Users/minhhieu76qng/dev/dsv/my-project/node_modules/hot-updater/dist/index.js:22633:30)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Command.init_init (file:///Users/minhhieu76qng/dev/dsv/my-project/node_modules/hot-updater/d …
```
> fix(cli): getCwd bundle failed on cloudflareD1R2Worker

- packages/react-native/android/src/main/java/com/hotupdater/HotUpdater.kt
- packages/react-native/ios/HotUpdater/HotUpdater.mm
- packages/react-native/src/native.ts
https://github.com/user-attachments/assets/f83b9f9f-e9ab-4cba-b0bd-d67517d2d4ab
* Caching Mechanism:
Instead of deleting the entire bundle-store on every update, the new implementation checks for a cached bundle using its bundleId. If found, the cached bundle is reused and the modification time of the final bundle directory is updated to keep it current. If not, the bundle is downloaded to a temporary directory (bundle-temp) and then moved to the final directory.
* Cleanup of Old Bundles:
A new cleanupOldBundles function removes all bundle directories in the bundle-store except for the two most recent ones, ensuring efficient disk space management.
* Instant Rollback:
With two bundles maintained, rollback now happens immediately without the need for a new download.
> feat(native): manage up to two bundles for immediate rollback

- packages/console/package.json
- packages/console/src/App.tsx
- packages/console/src/components/ui/layout.tsx
- packages/console/src/routes/index.tsx
- pnpm-lock.yaml
1. Splash screen displayed only on initial application entry.
2. Minimized data fetching frequency and eliminated visual flickering using @tanstack/solid-query's query key feature.
* (Note: solid-router version 0.14.10 prevents the direct usage of query in route components. Data prefetching or alternative strategies may be needed).
https://github.com/user-attachments/assets/4d097895-2a94-4a5f-bae1-95ae382cf779
Closed #131
> feat(console): Improve UX by preventing screen flickering

- packages/console/src-server/rpc.ts
- packages/hot-updater/src/commands/console.ts
- packages/hot-updater/src/commands/deploy.ts
- packages/hot-updater/src/config.ts
- plugins/plugin-core/src/loadConfig.ts
allow platform
```tsx
import { metro } from "@hot-updater/metro";
import { supabaseDatabase, supabaseStorage } from "@hot-updater/supabase";
import { defineConfig } from "hot-updater";
import "dotenv/config";
export default defineConfig(({ platform }) => { // Can be use platform
return {
build: metro({
enableHermes: platform === "ios",
}),
storage: supabaseStorage({
supabaseUrl: process.env.HOT_UPDATER_SUPABASE_URL!,
supabaseAnonKey: process.env.HOT_UPDATER_SUPABASE_ANON_KEY!,
bucketName: process.env.HOT_UPDATER_SUPABASE_BUCKET_NAME!,
}),
database: supabaseDatabase({
supabaseUrl: process.env.HOT_UPDATER_SUPABASE_URL!,
supabaseAnonKey: process.env.HOT_UPDATER_SUPABASE_ANON_KEY!,
}),
};
});
```
> feat(config): platform injected to config

- .vscode/settings.json
Setting the TypeScript version in the settings should allow for more consistency during development and make it less susceptible to the internal version of VS Code.
> Define workspace TypeScript version in settings

- packages/react-native/android/build.gradle
- packages/react-native/android/src/main/java/com/hotupdater/HotUpdater.kt
* As-is
getMinBundleId is based on the APK’s modification date, so when the app is freshly installed from the Play Store, it always gets updated to the latest version. As a result, update bundles created before the installation are ignored.
* To-be
getMinBundleId is fixed based on the build time, ensuring consistency regardless of the installation date.
> fix(android): keep a stable minBundleId on Android

- packages/hot-updater/src/commands/deploy.ts
- packages/hot-updater/src/index.ts
This Pull Request introduces the possibility of specifying the path where to store the `bundle.zip` before uploading it. After this addition, Hot Update will allow concurrently bundling of Android and iOS platforms.
> Allow to specify a custom output path for bundle.zip

- packages/react-native/android/src/main/java/com/hotupdater/HotUpdater.kt
- packages/react-native/ios/HotUpdater/HotUpdater.mm
Each download can contain up to two bundles, but this PR changes it to hold only one bundle.
> refactor(native): keep bundle latest bundle

- plugins/aws/tsup.config.ts
- plugins/cloudflare/tsup.config.ts
- plugins/firebase/tsup.config.ts
- plugins/supabase/tsup.config.ts
A banner with `import` syntax is injected in CommonJS modules, breaking the evaluation. The following are some evidences
> chore: Remove wrongly injected banner in cjs bundles

- .changeset/upset-mammals-bake.md
- packages/console/src-server/rpc.ts
- packages/console/src/routes/_components/data-table.tsx
- plugins/aws/src/s3Database.spec.ts
- plugins/cloudflare/src/d1Database.ts
- plugins/firebase/src/firebaseDatabase.spec.ts
- plugins/firebase/src/firebaseDatabase.ts
- plugins/mock/src/mockDatabase.ts
- plugins/mock/src/test/mockDatabase.spec.ts
- plugins/plugin-core/src/calculatePagination.ts
- plugins/plugin-core/src/createBlobDatabasePlugin.spec.ts
- plugins/plugin-core/src/createBlobDatabasePlugin.ts
- plugins/plugin-core/src/createDatabasePlugin.ts
- plugins/plugin-core/src/index.ts
- plugins/plugin-core/src/types/index.ts
- plugins/postgres/src/postgres.ts
- plugins/standalone/src/standaloneRepository.spec.ts
- plugins/standalone/src/standaloneRepository.ts
- plugins/supabase/iac/index.ts
- plugins/supabase/src/supabaseDatabase.ts
Currently, the console does not implement proper pagination functionality. The getBundles method only returns bundle data without pagination metadata, making it impossible to implement navigation controls or determine if additional pages are available.
---
To enable proper pagination in the console interface, this PR implements comprehensive changes to the data layer and providers
1. Update getBundles API specification
Before: getBundles() returns Promise<Bundle[]>
After: getBundles() returns Promise<{ data: Bundle[]; pagination: PaginationInfo }>
2. Update all database providers
Modify all existing database plugin implementations to support the new pagination response format
Ensure backward compatibility during the transition
Update type definitions across all affected modules
3. Update …
> fix: pagination

- .semgrepignore
[semgrep](https://semgrep.dev/docs/ignoring-files-folders-code) is a security scanner platform detects security issues from the source. We can include some paths to reduce the generated amount of security warning by semgrep.
I don't this is meaningful but resolve #338 partially.
The rule-based ignore seems impossible with `.semgrepignore` since it's a feature more open to user not library author. 
more than 90 issues -> 66 issues
5 supply chain issue -> gone
> chore: ignore some paths from semgrep security scan

- .changeset/twelve-papers-return.md
- docs/docs/guide/plugins/sentry.mdx
- plugins/sentry-plugin/package.json
- pnpm-lock.yaml
It seems we don't need to require `@sentry/cli` as `peerDependencies`.
`@hot-updater/plugin-sentry` should be integrated as dev dependencies, hence  we can safely import it to the our `dependencies`.
This is likely to resolve the problem user uses outdated sentry cli. 
related: #341
> fix(sentry): include standalone sentry cli in sentry plugin

- .changeset/tough-baboons-buy.md
- plugins/firebase/iac/index.ts
There is not default value of fieldoverrides.
It occurred concat error
```typescript
originalIndexes = originalStdout ?? { indexes: [], fieldOverrides: [] };
```
and add exact type for index
https://firebase.google.com/docs/reference/firestore/indexes?hl=ko
closed #407
> fix(firebase): index default

- .changeset/flat-actors-ring.md
- packages/hot-updater/src/utils/fingerprint/index.ts
- plugins/plugin-core/src/types/index.ts
Sometime I'd like to know which files or folders causing the fingerprint changed, I need to add debug option to show it
Add debug option when configuring hot updater
```
export default defineConfig({
build: bare({ enableHermes: true }),
...
fingerprint: {
debug: true,
}
});
```
> feat: add debug option while creating fingerprint

- .changeset/plain-roses-tickle.md
- packages/react-native/android/src/main/java/com/hotupdater/BundleFileStorageService.kt
- packages/react-native/ios/HotUpdater/Internal/BundleFileStorageService.swift
1. The app starts up by loading the existing bundle and launches based on it.
2. The hot-updater downloads a new bundle and deletes the existing bundle.
3. Since the assets that the existing bundle was accessing have disappeared, local images are no longer displayed.
1. Records of existing bundleIds and records of newly added bundleIds during the update process
2. In cleanupOldBundles, instead of keeping only the latest bundle as before, bundles corresponding to the above two parameters are not deleted
1. [x] - android
2. [x] - ios
> fix: delete previous bundle when previous bundle access is needed

- .changeset/red-worlds-lie.md
- packages/hot-updater/package.json
- pnpm-lock.yaml
Sometimes, if another package uses a different version of commander, hoisting can cause errors. To avoid this, we bundle commander directly into the CLI (via tsdown).
> chore(cli): move `commander` to `devDependencies` and bundle it

- .changeset/khaki-pillows-film.md
- packages/react-native/plugin/src/withHotUpdater.ts
In expo/expo#38576 the Android code template was changed slightly which causes hot-updater to inject it's kotlin code in an invalid location. When using the latest version of expo and trying to create an android build locally, the following error occurs:
```
[RUN_GRADLEW] > Task :app:compileReleaseKotlin FAILED
[RUN_GRADLEW] e: file:///private/var/folders/mn/pdfyttks06gf9tjjmxgrsxhh0000gn/T/eas-build-local-nodejs/66a2930f-0719-41f9-90b7-83d3f7fe369c/build/android/app/src/main/java/com/brongle/svag/MainApplication.kt:31:11 Modifier 'override' is not applicable to 'local function'.
```
And if we look at the generated MainApplication.kt file it's obvious our code was injected in the incorrect location:
```kotlin
override fun getPackages(): List<ReactPackage> = …
```
> fix: native android code generation fails on expo 54
